In [49]:
from sklearn import svm #importación de libreria de machine learning
import pandas as pd
import numpy as np

Abrir archivos que contienen la información para entrenamiento

In [50]:
Xp = pd.read_csv('X', delimiter=";")
Yp = pd.read_csv('Y', delimiter=";")

In [56]:
Yp.head()

COD
0    1
1    2
2    2
3    3
4    3

In [57]:
Xp.head()

C1        C2        C3
0  0.988296  0.887982  0.647662
1  0.429777  0.774242  0.467676
2  0.007227  0.728114  0.441992
3  0.315995  0.649296  0.637272
4  0.725780  0.324291  0.022826

In [59]:
X= np.zeros((50,3))
Y= np.zeros((50,3))

In [60]:
X = Xp.values #Para convertir en arreglos 
X.reshape(50,3)

array([[0.98829562, 0.88798206, 0.64766198],
       [0.42977716, 0.77424222, 0.46767635],
       [0.00722712, 0.72811441, 0.44199196],
       [0.31599465, 0.64929601, 0.63727242],
       [0.72577992, 0.32429099, 0.02282576],
       [0.09062185, 0.84873545, 0.07433727],
       [0.1867473 , 0.48246158, 0.89774317],
       [0.53047284, 0.57633295, 0.72544889],
       [0.06268501, 0.30668343, 0.95598187],
       [0.11087958, 0.47031782, 0.63852267],
       [0.77744742, 0.67253193, 0.01589405],
       [0.3392035 , 0.35100825, 0.04482766],
       [0.54973304, 0.69985096, 0.20681041],
       [0.12735229, 0.01130309, 0.50582208],
       [0.77458529, 0.22031595, 0.61997578],
       [0.08416211, 0.04217386, 0.67932524],
       [0.02946513, 0.57168092, 0.16676493],
       [0.55287543, 0.43206639, 0.39879743],
       [0.10748141, 0.11226164, 0.95916043],
       [0.32121347, 0.22392523, 0.66114609],
       [0.36605135, 0.19964318, 0.44251794],
       [0.52080886, 0.91205653, 0.12723775],
       [0.

In [62]:
Y = Yp.values
Y.reshape(50,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [2],
       [2],
       [1],
       [1],
       [3],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [3],
       [3],
       [1],
       [3],
       [2],
       [3],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [2],
       [1]])

In [63]:
regr = svm.SVR()

In [65]:
regr.fit(X.reshape(50,3),Y.reshape(50))

SVR()

In [66]:
regr.predict([[0.2499854505,0.7031572628,0.3994415088]])

array([2.58609001])